### ISSUE TITLE
create flat blender object ?

### ISSUE THREAD

**Issue by wrnice** [addam/Export-Paper-Model-from-Blender#43]
Hello !

I am trying to create an unfolded mesh inside blender, as a new object, not as a svg file.
Is it possible using your wonderful script ?
Or do you know a way to achieve this ?

The goal is to prototype fabric and plastic film shapes for real construction projects.

Thanks !

**Comment by addam** [comment]
Hi, unfolding the mesh in 3d is possible using the other script from this repository, `object_convert_to_armature.py`. The process consists basically of three steps:

1. Choose which edges should be cut to unfold the net
2. Actually cut the edges, creating doubled vertices as necessary
3. Flatten the mesh using an armature

Step 1. is done by the _Unfold_ button in _Paper Model_ tab. Step 2. has to be done by hand and using the _Edge Split_ operator; read the details on the [blender wiki](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Object/Convert_to_Armature), it is actually not hard. The last step is done by _Convert to Armature_. An armature will hopefully allow you to do everything you need.

This process is a bit complicated because I want my scripts not to modify mesh data if not necessary; because of that, you have to split the edges yourself.

**Comment by wrnice** [comment]
Thank you ! This will do just what is needed !
