### ISSUE TITLE
Texture is rendered incorrectly

### ISSUE THREAD

**Issue by sybrenstuvel** [addam/Export-Paper-Model-from-Blender#45]
I'm trying to project an equirectangular image onto an icosphere. This is my blend file
[bugreport.blend.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/468304/bugreport.blend.zip)

Instead of the texture as seen in the viewport & renders, I get this:

![generated_image](https://cloud.githubusercontent.com/assets/1092128/18451855/e64a1c3c-7938-11e6-9f06-568d3a32c904.png)

What I expected is an unwrap of this:

![viewport](https://cloud.githubusercontent.com/assets/1092128/18451919/37f102da-7939-11e6-806d-874c00ced0e6.png)

This is with both the version shipped with Blender-2.78-rc1 as the latest from this git repo's master branch.

**Comment by jdugge** [comment]
This is an issue that's not related to the Export Paper Model plugin, you will see the same behaviour if you set the "Viewport Shading" in the 3D view to "Rendered" instead of "Texture".

To fix this, set the "Projection" of the "Mapping" in the "Texture" tab to "Flat" instead of "Sphere":

![screenshot from 2016-09-13 12 39 23](https://cloud.githubusercontent.com/assets/2399255/18470970/8a0e7946-79af-11e6-927f-7ab42b5e6715.png)

**Comment by sybrenstuvel** [comment]
Excellent, thanks for the quick reply!
