### ISSUE TITLE
Error: Circular reference in texture stack

### ISSUE THREAD

**Issue by MayeoinBread** [addam/Export-Paper-Model-from-Blender#54]
Hi,
I'm starting to get issues when trying to export a model with a painted texture. I have everything set up as described on the wiki page (and as I have done many times before), but every time I try export the model with the texture (using Blender Internal), I get a "Circular reference in texture stack" error.
![image](https://user-images.githubusercontent.com/22642663/27560552-8878b72e-5abc-11e7-9eda-70ae81588c56.png)

When I try export using Cycles, I get the below error.
![image](https://user-images.githubusercontent.com/22642663/27560392-ed54b2f2-5abb-11e7-8545-6ddc88e320f7.png)

I have also tried with older meshes (from at least a year or two ago) where it used to work, and I get the same issues. Part of me is hoping I've just forgotten something really obvious!

-Eoin

**Comment by addam** [comment]
These errors are evil. I remember I spent a few days debugging them, and that I had finally figured out what they are trying to say, but I no longer remember that.

The method `save_image` used to begin like this:
```
    def save_image(self, tex, page_size_pixels: M.Vector, filename):
        texfaces = tex.data
        # omitting this causes a "Circular reference in texture stack" error
        for island in self.islands:
            for uvface in island.faces:
                texfaces[uvface.face.index].image = None
```
A while ago I realized that the code works without this hack and I removed it -- but perhaps things have once again changed for the worse. The last version that includes this workaround is [e4d373](https://github.com/addam/Export-Paper-Model-from-Blender/blob/e4d373589b6027205e5236b096ff9a32fa4ebb7b/io_export_paper_model.py), you can try it for now.

The Cycles error is something different and should be easy to fix, I'll look into it tomorrow.

**Comment by MayeoinBread** [comment]
Ah great! Thanks, that works.

**Comment by comac2k** [comment]
I resumed some of my models this week just to stumble upon this problem myself. Here's what I've found:

- Version e4d373 works (after some editing since it insisted in naming the linked images folder exactly the same as the final svg file and was looking for a "path" property that doesn't seem to exist in Image objects anymore).
- Latest master version fails with circular reference.
- Latest master version with the hack in place (cut & paste from the old version) fails too.
- Latest master version works when using "linked single" and the model can be exported to just one page.

Does this give any clues?

**Comment by Tymski** [comment]
On 2.79 addon doesn't work either.
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_export_paper_model.py", line 2194, in execute
    self.unfolder.save(self.properties)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_export_paper_model.py", line 315, in save
    self.mesh.save_separate_images(tex, ppm, filepath, embed=Exporter.encode_image)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_export_paper_model.py", line 668, in save_separate_images
    bake([uvface.face.index for uvface in island.faces], tex, image)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_export_paper_model.py", line 212, in bake
    bpy.ops.object.bake_image()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Circular reference in texture stack

location: <unknown location>:-1
```

**Comment by addam** [comment]
I've put back that magic piece of code, and I believe Blender Internal baking works again. @Tymski, can you please check the current master with your scene?

While investigating Cycles baking I realised it never might have worked. I'll read the documentation but all the options of baking an image in Cycles seem awfully complicated.

**Comment by Tymski** [comment]
Tried it with a cube and a uv grid. Works fine.

**Comment by gatobarbado** [comment]
Hello, I am having trouble with the Paper Model add-on, currently I am using version 2.79, I have tried a lot of different stuff but nothing seems to work, my model exports fine without a texture but all crashes when I try to export it with a custom drawing. I will appreciate any help. Thanks

**Comment by comac2k** [comment]
@gatobarbado are you using the version of the plugin bundled with blender? You might want to download the latest version from the repo and make sure you're using that one. Failure to export with textures was a known issue that was fixed in the repo but not included (yet) in the official blender distribution. Also, if you're exporting to separate images, make sure there's no folder with the same name as the destination file (minus extension).

**Comment by addam** [comment]
@gatobarbado, it should be enough to download blender 2.79b, I hope I have fixed this issue. Or not?
