### ISSUE TITLE
Add curvature modeling support 

### ISSUE THREAD

**Issue by wvlia5** [addam/Export-Paper-Model-from-Blender#57]
Imagine I wanted to make a smooth cylinder. I would have to make a mesh with a lot of facets. Instead, I could just used a single curved sheet.
This would simplify construction of models, since a quad can be represented with the four resulting parameters (3 × plane + 1 × curvature) so there would be no need for triangulation.

**Comment by wvlia5** [comment]
[This](https://matiasmorant.wordpress.com/2017/12/23/papercraft-with-blender/)  is what I made with your script, thanks

**Comment by addam** [comment]
There are very few tools for editing such smooth surfaces in Blender. Coding them is far beyond the scope of this script.

Another difficulty with curved surfaces are the sticking tabs since they usually have to be split into a lot of tiny parts along the curved edge.

The suggested approach is to subdivide the mesh as you wish, and increase the "Hidden Edge Angle" so that the curved folds disappear from the net.
