### ISSUE TITLE
Attribute Error: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'

### ISSUE THREAD

**Issue by Thera-code** [addam/Export-Paper-Model-from-Blender#94]
I added a UV sphere, marked all the vertical edges as seams, added a material to which I assigned an image as a base and then tried to export it using this add on and every option to include textures, upon which i got this error:
`Attribute Error: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'`
Thats not tge full error message but it wouldn't let me copy the text for whatever reason. Let me know if you need that, and I'll get it to you somehow.
If I try to export it without the material added but still with the include materials option(s) this also occurs.
Using a single color texture also does not help.
Rebooting or restarting Blender or re-enabling the add-on didn't work either.

**Comment by DanielFlaum** [comment]
I'm also experiencing this with add-on version 1.2 and Blender 3.0.0. I'll prepare a `.blend` that reproduces the issue.

**Comment by DanielFlaum** [comment]
The attached `.blend` reproduces the issue for me: [broken-paper-model.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/7732475/broken-paper-model.zip).

**Comment by DanielFlaum** [comment]
I was able to fix this issue by editing my copy of `io_export_paper_model.py` to remove all mentions of ambient occlusion. But that file doesn't appear in this repository, and I'm not knowledgeable about Blender add-on build processes.

Here, however, is a `.zip` with my changes: [io_export_paper_model_fix.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/7732601/io_export_paper_model_fix.zip).

**Comment by Thera-code** [comment]
That works for me, thank you.

In the original file there appears to be a task list which says:
> # Task: split into four files (SVG and PDF separately)
and it looks to me as if that has already happened in this repo, so applying the fix you provided should not be an issue, however I am unsure if just removing ambient occlusion really is a permanent fix.

**Comment by addam** [comment]
@DanielFlaum, thank you for the fix. Apparently, the Ambient Occlusion pass was actually removed from Bake render settings.

Still, it is possible to use Ambient Occlusion as a specific Bake Type and I believe this option is useful. Here is a fixed version of the script with only the necessary bits removed while keeping all functionality: [io_export_paper_model_fix.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/7761830/io_export_paper_model_fix.zip)

@Thera-code, thank you for this bugreport and please excuse that it took me this long before I got to fixing it. The code is now updated both here and in the official repo, so that next Blender release will have the script properly working -- thanks to you.
